# Change these first
owner: lucordes # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Overleaf
    url: https://overleaf.lucacordes.com
  - name: Landingpage
    url: https://www.lucacordes.com
  - name: Notes
    url: https://notes.lucacordes.com
  - name: Gitea
    url: https://git.lucacordes.com
  - name: Budget
    url: https://budget.lucacordes.com
  - name: Analytics
    url: https://analytics.lucacordes.com
  - name: Photos
    url: https://photos.lucacordes.com
  - name: Orderfood
    url: https://orderfood.lucacordes.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.lucacordes.com
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "[**lucacordes.com**](https://www.lucacordes.com) monitor"
  introMessage: The tracking does not take place on the hardware of the server but is entirely powered by GitHub.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
